# Generated by Django 5.2.8 on 2025-11-26 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(blank=True, help_text='e.g. Dark fantasy, psychological horror', max_length=100)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags, e.g. 'dark fantasy, cult, catacombs'", max_length=250)),
                ('summary', models.TextField(blank=True, help_text='Short description of the story.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='What you did for this story in this update.')),
                ('words_added', models.PositiveIntegerField(blank=True, help_text='How many words you added in this update (optional).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='storytracker.story')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
